### ISSUE TITLE
提交bug

### ISSUE THREAD

**Issue by wfxiaolong** [pupuk/address-smart-parse#2]
区判断的代码是错误的：
内蒙古自治区乌兰察布市公安局交警支队车管所：常琦1864742989
攀枝花市东区攀枝花三中高三班2010级

**Comment by pupuk** [comment]
已收到。如有兴趣，看看先能自己修复一下不？我等这两日天手中项目完成，就来修复。

**Comment by wfxiaolong** [comment]
哈哈，我那天顺手已经修复了，参考你写的php版本，我写的是个js的版本...不一样...

**Comment by pupuk** [comment]
谢谢，麻烦你提供下PHP的版本的修复文件的diff，我好合并到我们这个上面去。我的邮箱是pujiexuan@gmail.com ，谢谢了。我已经follow你啦

**Comment by wfxiaolong** [comment]
[address.js.zip](https://github.com/pupuk/address-smart-parse/files/2113208/address.js.zip)

js 的修订版本。我实在是没有精力去看代码。。。

**Comment by pupuk** [comment]
谢谢，麻烦你start一下我的项目，给我点个星星哈
https://github.com/pupuk/address-smart-parse
